### ISSUE TITLE
EconomyPShop Not Saving

### ISSUE THREAD

**Issue by Haxley** [poggit-orphanage/EconomyS#12]
EconomyPShop doesn't seem to be saving player shops to the shops.yml file after a server reboot, since Alpha 10. EconomyLand, EconomySell, EconomyShops all still save just fine after reboot.

**Comment by Awzaw** [comment]
This must have been a problem since the changes to SignChangeEvent... I'm updating it now to use a similar command system to EconomyShop

**Comment by Awzaw** [comment]
Please test the latest release: https://poggit.pmmp.io/p/EconomyPShop.
I've used code from the updated EconomyShop plugin so you create PShops exactly as you do for regular Shops using the command `/pshop create <item> <amount> <price> [side]`, and they should display as the Item floating to the chosen `side` (optional) of the block.

To remove a shop, either the shop owner or OP/player with the `economypshop.shop.destroy.others` permission can break it. Also, updates to Shops.yml are now saved on creation/deletion. Please report bugs here.

**Comment by Haxley** [comment]
Awesome, thanks so much! Not only can I confirm that this fixed it, but I think this is better all around 'cause now players can make their shop signs look however they please. Nice work!
