### ISSUE TITLE
EconomyPShops Only Sell Amount 1 of Item

### ISSUE THREAD

**Issue by Haxley** [poggit-orphanage/EconomyS#13]
When you make a pshop, regardless of the amount you tell it to sell, it will only sell 1 of that item.

**Comment by Awzaw** [comment]
Can you try again now with the release: https://poggit.pmmp.io/p/EconomyPShop/

**Comment by Haxley** [comment]
Awesome, fixed!

**Comment by Awzaw** [comment]
I'd only ever tested with 1...
