### ISSUE TITLE
Player shop creation

### ISSUE THREAD

**Issue by optimusprime338** [poggit-orphanage/EconomyS#14]
Its so annoying that players can make shop everywhere! even on blocks so can it fixed so players can only make shops on signs using economypshop? can it have limitations of creating player shop? If yes that would be awesome!!'
You need to bring back sign method for this system since players scamms a lot with this one!

**Comment by Awzaw** [comment]
The sign method was removed by onebone in Shop because the client changed and there is no longer event on closing signs, and I've used the same approach in PShop. There should still be the permissions restrictions though, don't they work? And I'll check the block check

**Comment by Awzaw** [comment]
I've added a boolean option `allow-any-block` to the config of EconomyShop and EconomyPShop
