### ISSUE TITLE
Shop and Sell Removal Broken?

### ISSUE THREAD

**Issue by Haxley** [poggit-orphanage/EconomyS#21]
I haven't been able to /shop remove or /sell remove for some time now, including with most recent version. You must use the remove command and tap directly in the center of the item displayer to get the "shop was removed successfully" text, but still It doesn't ever remove the shop. What's more, you cannot destroy blocks that shops are on, so the only way to delete a shop or edit the block a shop is on (i.e. a sign), you have to edit the yaml file and restart the server.

**Comment by brexmania123** [comment]
i have noticed that too

**Comment by YTiStrafeNubzHD** [comment]
me too

**Comment by Awzaw** [comment]
I'll try to find time to fix that this week if nobody makes a PR

**Comment by Awzaw** [comment]
Fixed in 029cb3d0758
