### ISSUE TITLE
spam click (EconomyShop)

### ISSUE THREAD

**Issue by llronaldoll** [poggit-orphanage/EconomyS#30]
when I click to buy, a spam happens and the purchase is made several times (EconomyShop)

**Comment by Awzaw** [comment]
I can't reproduce this - do you have any plugins installed which might replay clicks?

**Comment by MSG100TC** [comment]
Same issue

**Comment by Awzaw** [comment]
Fixed in 1bd4d285709, you now have to move between purchases.
