### ISSUE TITLE
Signs are not working anymore

### ISSUE THREAD

**Issue by MSG100TC** [poggit-orphanage/EconomyS#40]
Hello. Sell and Shop Signs not are working anymore. I'm using EconomyAPI 5.7.3 and latest version of EconomySell. PMMP Version: 3.5.1

I made sure that I had the sign format correctly.

**Comment by MSG100TC** [comment]
@Awzaw

**Comment by MSG100TC** [comment]
And nothing shows up when you do /sell

**Comment by Awzaw** [comment]
Sorry for the very late reply. To make a shop you type ` /shop create 276 1 500``` for example, then click the block (or sign you made). Same for /sell... it's in the EconomyS docs.
