### ISSUE TITLE
#bug Unable to change language to Chinese

### ISSUE THREAD

**Issue by dizicheng** [poggit-orphanage/EconomyS#41]
/setlang Unable to change language to Chinese

**Comment by Awzaw** [comment]
<img width="441" alt="Screenshot 2019-03-20 at 00 48 08" src="https://user-images.githubusercontent.com/10437212/54649302-e85f5100-4aa9-11e9-93e1-b71347a9d91d.png">
<img width="663" alt="Screenshot 2019-03-20 at 00 49 34" src="https://user-images.githubusercontent.com/10437212/54649337-13e23b80-4aaa-11e9-9b71-dbb50927a750.png">
