### ISSUE TITLE
Line 89

### ISSUE THREAD

**Issue by ZZWILLIAMXXTrue** [poggit-orphanage/EconomyS#53]
10.11 16:07:00 [Server] Server thread/INFO Enabling EconomyAPI v5.7.3
10.11 16:07:00 [Server] Server thread/NOTICE Something went wrong on update server.
10.11 16:07:00 [Server] Server thread/NOTICE Database provider was set to: Yaml
10.11 16:07:00 [Server] Server thread/CRITICAL ErrorException: "Undefined index: mymana" (EXCEPTION) in "plugins/EconomyAPI.phar/src/onebone/economyapi/EconomyAPI" at line 89
10.11 16:07:00 [Server] Server thread/DEBUG #0 plugins/EconomyAPI.phar/src/onebone/economyapi/EconomyAPI(89): pocketmine\utils\Utils::errorExceptionHandler(integer 8, string[23] Undefined index: mymana, string[115] phar:///plugins/EconomyAPI.phar/sr, integer 89, array[2])
10.11 16:07:00 [Server] Server thread/DEBUG #1 plugins/EconomyAPI.phar/src/onebone/economyapi/command/MyMoneyCommand(17): onebone\economyapi\EconomyAPI->getCommandMessage(string[6] mymana)
10.11 16:07:00 [Server] Server thread/DEBUG #2 plugins/EconomyAPI.phar/src/onebone/economyapi/EconomyAPI(423): onebone\economyapi\command\MyMoneyCommand->__construct(object onebone\economyapi\EconomyAPI)
10.11 16:07:00 [Server] Server thread/DEBUG #3 plugins/EconomyAPI.phar/src/onebone/economyapi/EconomyAPI(382): onebone\economyapi\EconomyAPI->registerCommands()
10.11 16:07:00 [Server] Server thread/DEBUG #4 plugins/EconomyAPI.phar/src/onebone/economyapi/EconomyAPI(307): onebone\economyapi\EconomyAPI->initialize()
10.11 16:07:00 [Server] Server thread/DEBUG #5 src/pocketmine/plugin/PluginBase(123): onebone\economyapi\EconomyAPI->onEnable()
10.11 16:07:00 [Server] Server thread/DEBUG #6 src/pocketmine/plugin/PluginManager(580): pocketmine\plugin\PluginBase->setEnabled(boolean 1)
10.11 16:07:00 [Server] Server thread/DEBUG #7 src/pocketmine/Server(2002): pocketmine\plugin\PluginManager->enablePlugin(object onebone\economyapi\EconomyAPI)
10.11 16:07:00 [Server] Server thread/DEBUG #8 src/pocketmine/Server(1988): pocketmine\Server->enablePlugin(object onebone\economyapi\EconomyAPI)
10.11 16:07:00 [Server] Server thread/DEBUG #9 src/pocketmine/Server(1782): pocketmine\Server->enablePlugins(integer 1)
10.11 16:07:00 [Server] Server thread/DEBUG #10 src/pocketmine/PocketMine(278): pocketmine\Server->__construct(object BaseClassLoader, object pocketmine\utils\MainLogger, string[47] /, string[55] /plugins/)
10.11 16:07:00 [Server] Server thread/DEBUG #11 src/pocketmine/PocketMine(300): pocketmine\server()
10.11 16:07:00 [Server] Server thread/DEBUG #12 (1): require(string[107] phar:///PMMP-Latest-Stable.phar/sr)
10.11 16:07:00 [Server] Server thread/INFO Disabling EconomyAPI v5.7.3

**Comment by Awzaw** [comment]
Why /mymana? Did you set that up in the selected language file?

**Comment by jaylac2000** [comment]
your server is out of date? what version is ur server?

**Comment by ZZWILLIAMXXTrue** [comment]
Idk
